# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53b09d495ff2d419323dd58a340158bba802ed79bcae4c9e969e8452da9ff6722e8c402afb7ae88ed429d269065ce38013b52508628abdf63fbaf9098e4a8df8

test:
  secret_key_base: cad96005c0954704dc9ad0a2b7f4b0933982b134f9c47cb98565211685b8cd825397a4ceb379d165a4ee88cf254ca828eb0a2d3d5f5d44276fa4c3c613e154e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: a50ce332cb93557f9ed1a53dae7bc78858e41517647883e417b8b5ed81de9068763e19608257a43712861a161728223b3a01f235102ca7649be9f47c4c2c79e0
